#ifndef MAINWINDOW_H
#define MAINWINDOW_H

/**
 * @file mainwindow.h
 *
 * @brief Header file for the MainWindow class, which serves as the
 *        welcome screen of the PC Builder educational application.
 *
 * This class displays an animated PC icon using Box2D physics and transitions
 * the user into the LearningWindow when the Start button is clicked.
 *
 * @date 04/22/2025
 */

#include "learningwindow.h"

#include <QGraphicsPixmapItem>
#include <QGraphicsScene>
#include <QMainWindow>
#include <QTimer>
#include <Box2D/Box2D.h>

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

/**
 * @class MainWindow
 *
 * @brief The MainWindow class handles the welcome screen of the app,
 *        featuring a physics-based animation and a button to enter the
 *        learning portion of the PC Builder experience.
 */
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:

    /**
     * @brief Constructor for MainWindow.
     * @param learningWindow Pointer to the LearningWindow for navigation.
     * @param parent Optional parent widget.
     */
    MainWindow(LearningWindow* learningWindow, QWidget* parent = nullptr);

    /**
     * @brief Destructor for MainWindow.
     */
    ~MainWindow();

private:

    /**
     * @brief Pointer to the UI layout generated by Qt Designer.
     */
    Ui::MainWindow* ui;

    /**
     * @brief Pointer to the LearningWindow to allow navigation on button press.
     */
    LearningWindow* learningWindow;

    /**
     * @brief Qt graphics scene for displaying the PC icon.
     */
    QGraphicsScene* scene;

    /**
     * @brief Pixmap item representing the PC icon.
     */
    QGraphicsPixmapItem* pcIconItem;

    /**
     * @brief Box2D world object for physics simulation.
     */
    b2World* world;

    /**
     * @brief Box2D body for the animated PC icon.
     */
    b2Body* pcIconBody;

    /**
     * @brief Timer that drives the frame-by-frame animation of the PC icon.
     */
    QTimer animationTimer;

private slots:

    /**
     * @brief Slot triggered when the Start button is clicked.
     *        Transitions the user into the LearningWindow.
     */
    void onStartButtonClicked();

    /**
     * @brief Slot for updating the animation frame using Box2D physics.
     */
    void frameAnimation();

};

#endif // MAINWINDOW_H
